<html>
<head>
</head>
<body>

    <!-- NAME: navi.tpl -->
<HTML>
<HEAD>
<TITLE> O N L I N E - P L A Y E R S - A S S O C I A T I O N  </TITLE>

<style type="text/css">
<!-
A { text-decoration:none }
->
</style>

<STYLE TYPE="text/css">
}
INPUT {
	FONT-FAMILY: verdana,arial,helvetica; FONT-SIZE: 8pt
P {
	COLOR: #ffffff; FONT-FAMILY: verdana,arial,helvetica; FONT-SIZE: 8pt; MARGIN: 0px TEXT-ALIGN: justify
TD {
	COLOR: #ffffff; FONT-FAMILY: verdana,arial,helvetica; FONT-SIZE: 7pt; MARGIN: 0px
H5 {
	COLOR: #ffcc00; FONT-FAMILY: verdana,arial,helvetica; FONT-SIZE: 7pt; MARGIN-BOTTOM: 0px; MARGIN-TOP: 0px; PADDING-BOTTOM: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px
</STYLE>

</HEAD>

<BODY BGCOLOR=000000 LINK=#ffcc00 vlink=#ffcc00>
<CENTER>
<TABLE WIDTH="474" CELLSPACING="0" CELLPADDING="0" border="0"><TR BGCOLOR="#FFFFFF">
<TD colspan=1><IMG SRC="../imgcom/clear.gif" ALT="" HEIGHT=1></TD></TR></TABLE>
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr bgcolor=#ffffff><td bgcolor=#FFFFFF width="1" align=left><img src="../imgcom/clear.gif" alt="" width=1 height=1></td><td colspan=1 height=66 bgcolor=#444444 align=center valign=middle>
<center><a href="http://www.onlineplayersassociation.co.uk"><img src="../banners/olpa.gif" width=468 height=60 border=0></a></td><td bgcolor=#FFFFFF width="1" align=right><img src="../imgcom/clear.gif" alt="" width=1 height=1></td></tr>
</table><table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" height=1></td></tr></table>
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr><td bgcolor=#FFFFFF width="1" align=left><img src="../imgcom/clear.gif" alt="" width=1 height=1></td><TD bgcolor=#ff0000><a href="clear.php3"><img src="../imgcom/clear.gif" width=183 height=10 border=0></a><img src="../imgcom/clear.gif" width=288 height=10></TD><td bgcolor=#FFFFFF width="1" align=right><img src="../imgcom/clear.gif" alt="" width=1 height=1></td></tr>
</table>
<table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" width=474 height=1></td></tr>
</table>
<table width="474" cellspacing="0" cellpadding="0" border="0"><tr>
<td colspan=1><img src="../imgcom/clear.gif" Alt="" width=474 height=5></td></tr>
</table>
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" height=1></td></tr></table>
<!-- END: topban.tpl --><!-- NAME: page1.tpl -->
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr><td bgcolor=#FFFFFF width="1" align=left><img src="../imgcom/clear.gif" alt="" width=1 height=1></td><td colspan=1 bgcolor=#444444 align=left><font face='arial' size='2' color='#ffffff'>&nbsp;<b><A HREF="http://www.onlineplayersassociation.co.uk/casino.php3">Casinos Join</a><IMG SRC="../imgcom/clear.gif" ALT="" WIDTH=15 HEIGHT=1 border=0>  <font face='arial' size='2' color='#ffffff'> <b>  <A HREF="http://www.onlineplayersassociation.co.uk/players.php3">Players Join</a><IMG SRC="../imgcom/clear.gif" ALT="" WIDTH=15 HEIGHT=1 border=0> <A HREF="http://www.onlineplayersassociation.co.uk/supporters.php3">Supporters Join</a><IMG SRC="../imgcom/clear.gif" ALT="" WIDTH=15 HEIGHT=1 border=0><a href="mailto:support@onlineplayersassociation.co.uk?subject=OPA : Support">Contact Us</a><IMG SRC="../imgcom/clear.gif" ALT="" WIDTH=15 HEIGHT=1 border=0><A
HREF="http://www.onlineplayersassociation.co.uk/legal.php3">Legal</a></i></td><td bgcolor=#FFFFFF width="1" align=right><img src="../imgcom/clear.gif" alt="" width=1 height=1></td></tr>
</table><table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" width=474 height=1></td></tr>
</table>
<table width="470" cellspacing="0" cellpadding="0" border="0">
<tr><td><font face='arial' size='2' color='#ffffff'><br>

<a href="http://www.onlineplayersassociation.co.uk" ><img src="../banners/back.gif" border=0></a><img src="../imgcom/opaORIGSMALL.gif"><src="../imgcom/APPROVED.gif"><br><br>
<B>
<CENTER>
The following are OPA Approved Casinos<br><br></CENTER>


<a href="http://www.casinofortune.com"><img src="../banners/FORTUNE.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>

<a href="http://www.miamibeachcasino.com"><img src="../banners/MIAMI.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>

<a href="http://www.goldgatecasino.com"><img src="../banners/GGATE.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>

<a href="http://www.mapau.com"><img src="../banners/mapau.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>

<a href="http://www.flashwins.com"><img src="../banners/flashwins.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
  <center>
 
  <a href="http://www.goodasgoldcasino.com"><img src="../banners/gag.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
  <center>
<a href="http://www.kingneptunescasino.com"><img src="../banners/kn.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
  <center>

<a href="http://www.newyorkcasino.com"><img src="../banners/newyork468.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
  <center>
<a href="http://www.thespinroom.com"><img src="../banners/spinroom.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
  <center>
<a href="http://www.stanleyacropolis.com"><img src="../banners/stanley.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
  <center>
<a href="http://www.swisscasino.com"><img src="../banners/swiss468.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
  <center>
<a href="http://www.acekingclubcasino.com"><img src="../banners/akc.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
<a href="http://www.silverdollarcasino.com"><img src="../banners/sd.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>

  <center>
<a href="http://www.casinokingdom.com"><img src="../banners/ck468b06.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
  <center>

<a href="http://www.usacasino.com"><img src="../banners/usa468.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>

<a href="http://www.drholite.com"><img src="../banners/drho.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>

<a href="http://www.englishharbourcasino.com"><img src="../banners/eharb.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>

<a href="http://www.intercasino.com"><img src="../banners/interc.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
<a href="http://www.captaincookscasino.com"><img src="../banners/cook1.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br><a href="http://www.theplayersroom.com"><img src="../banners/tpr.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
<a href="http://www.vipcasinos.com"><img src="../banners/vipc.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
<a href="http://www.wssbcasino.com"><img src="../banners/wss.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
<a href="http://www.superslots.com"><img src="../banners/superslots.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
<a href="http://www.sterlinghousecasino.com"><img src="../banners/sterlinghouse.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
<a href="http://www.casinotropez.com"><img src="../banners/tropez468.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
  <center>
<a href="http://www.millionairecasino.com"><img src="../banners/MCa040202a.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>

<br><br>
<a href="http://www.clubdicecasino.com"><img src="../banners/clubdice468.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br><a <a href="http://www.caribbeangoldcasino.com"><img src="../banners/caribbeangold-468x60.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>

<a href="http://www.blackjackplayer.com"><img src="../banners/bjp14.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>

<a href="http://www.casinobleublancrouge.com"><img src="../banners/BBRa051602a.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
<href="http://www.apostecasino.com"><img src="../banners/APa100301c.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
<a href="http://www.grandbankscasino.com"><img src="../banners/468gbf.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a><br><br>
<a href="http://ad.doubleclick.net/jump/N1684.OPA/B957543;sz=468x60;ord=[timestamp]?"><img src="http://ad.doubleclick.net/ad/N1684.OPA/B957543;sz=468x60;ord=[timestamp]?" width="468" height="60" border="0" alt="OPA APPROVED"></a>

 <br><br>
**The OPA does NOT subscribe to ANY profit sharing or affiliate type programmes<br><br>


  <center>
To contact The OPA <a href="mailto:support@onlineplayersassociation.co.uk?subject=OPA: SUPPORT">CLICK HERE</a><br><br>

 </font><br><br>
          </td>
        </tr>

      </table>
<table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" height=1></td></tr></table>
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr><td bgcolor=#FFFFFF width="1" align=left><img src="../imgcom/clear.gif" alt="" width=1 height=1></td><td colspan=1 height=66 bgcolor=#444444 align=center valign=middle>
<center><a href="http://www.onlineplayersassociation.co.uk"><img src="../banners/olpa.gif" width=468 height=60 border=0></td><td bgcolor=#FFFFFF width="1" align=right><img src="../imgcom/clear.gif" alt="" width=1 height=1></td></tr>
</table><table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" height=1></td></tr></table>
</BODY>
</HTML>

  

