<html>
<head>
</head>
<body>

    <!-- NAME: navi.tpl -->
<HTML>
<HEAD>
<TITLE> O N L I N E - P L A Y E R S - A S S O C I A T I O N  </TITLE>

<style type="text/css">
<!-
A { text-decoration:none }
->
</style>

<STYLE TYPE="text/css">
}
INPUT {
	FONT-FAMILY: verdana,arial,helvetica; FONT-SIZE: 8pt
P {
	COLOR: #ffffff; FONT-FAMILY: verdana,arial,helvetica; FONT-SIZE: 8pt; MARGIN: 0px TEXT-ALIGN: justify
TD {
	COLOR: #ffffff; FONT-FAMILY: verdana,arial,helvetica; FONT-SIZE: 7pt; MARGIN: 0px
H5 {
	COLOR: #ffcc00; FONT-FAMILY: verdana,arial,helvetica; FONT-SIZE: 7pt; MARGIN-BOTTOM: 0px; MARGIN-TOP: 0px; PADDING-BOTTOM: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px
</STYLE>

</HEAD>

<BODY BGCOLOR=000000 LINK=#ffcc00 vlink=#ffcc00>
<CENTER>
<TABLE WIDTH="474" CELLSPACING="0" CELLPADDING="0" border="0"><TR BGCOLOR="#FFFFFF">
<TD colspan=1><IMG SRC="../imgcom/clear.gif" ALT="" HEIGHT=1></TD></TR></TABLE>
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr bgcolor=#ffffff><td bgcolor=#FFFFFF width="1" align=left><img src="../imgcom/clear.gif" alt="" width=1 height=1></td><td colspan=1 height=66 bgcolor=#444444 align=center valign=middle>
<center><a href="http://www.onlineplayersassociation.co.uk"><img src="../banners/olpa.gif" width=468 height=60 border=0></a></td><td bgcolor=#FFFFFF width="1" align=right><img src="../imgcom/clear.gif" alt="" width=1 height=1></td></tr>
</table><table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" height=1></td></tr></table>
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr><td bgcolor=#FFFFFF width="1" align=left><img src="../imgcom/clear.gif" alt="" width=1 height=1></td><TD bgcolor=#ff0000><a href="clear.php3"><img src="../imgcom/clear.gif" width=183 height=10 border=0></a><img src="../imgcom/clear.gif" width=288 height=10></TD><td bgcolor=#FFFFFF width="1" align=right><img src="../imgcom/clear.gif" alt="" width=1 height=1></td></tr>
</table>
<table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" width=474 height=1></td></tr>
</table>
<table width="474" cellspacing="0" cellpadding="0" border="0"><tr>
<td colspan=1><img src="../imgcom/clear.gif" Alt="" width=474 height=5></td></tr>
</table>
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" height=1></td></tr></table>
<!-- END: topban.tpl --><!-- NAME: page1.tpl -->
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr><td bgcolor=#FFFFFF width="1" align=left><img src="../imgcom/clear.gif" alt="" width=1 height=1></td><td colspan=1 bgcolor=#444444 align=left><font face='arial' size='2' color='#ffffff'>&nbsp;<b><A HREF="http://www.onlineplayersassociation.co.uk/casino.php3">Casinos Join</a><IMG SRC="../imgcom/clear.gif" ALT="" WIDTH=15 HEIGHT=1 border=0>  <font face='arial' size='2' color='#ffffff'> <b>  <A HREF="http://www.onlineplayersassociation.co.uk/players.php3">Players Join</a><IMG SRC="../imgcom/clear.gif" ALT="" WIDTH=15 HEIGHT=1 border=0> <A HREF="http://www.onlineplayersassociation.co.uk/supporters.php3">Supporters Join</a><IMG SRC="../imgcom/clear.gif" ALT="" WIDTH=15 HEIGHT=1 border=0><a href="mailto:support@onlineplayersassociation.co.uk?subject=OPA : Support">Contact Us</a><IMG SRC="../imgcom/clear.gif" ALT="" WIDTH=15 HEIGHT=1 border=0><A
HREF="http://www.onlineplayersassociation.co.uk/legal.php3">Legal</a></i></td><td bgcolor=#FFFFFF width="1" align=right><img src="../imgcom/clear.gif" alt="" width=1 height=1></td></tr>
</table><table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" width=474 height=1></td></tr>
</table>
<table width="470" cellspacing="0" cellpadding="0" border="0">
<tr><td><font face='arial' size='2' color='#ffffff'><br>

<a href="http://www.onlineplayersassociation.co.uk" ><img src="../banners/back.gif" border=0></a><img src="../imgcom/AWARD.gif"></CENTER><br><B>
The following Casinos have been voted "best of" in The 2002 OPA Awards. Many thanks to all who submitted their votes and congratulations to the Casinos who were voted top for 2002.We ensured that no casino offered a player incentive to vote thus ensuring each casino won on merit.
<br><br>
<CENTER>Best OPA Approved Casino</CENTER>
<CENTER>INTERCASINO</CENTER>
<a href="http://www.intercasino.com/index.php3?498" target=new><IMG SRC="../imgcom/interc.gif" border=0></a>
<br>
<CENTER> Quickest Payouts Award</CENTER>
<CENTER>Miami Beach Casino</CENTER>
<a href="http://www.miamibeachcasino.com" target=new ><IMG SRC="../imgcom/MIAMI.gif" border=0></a>
<br>
<CENTER> Best Casino Game Award</CENTER>
<CENTER>Microgaming "Power Poker"</CENTER><a href="http://www.captaincookscasino.com/download.asp?Btag=1waopa1002" target=new><img src="../imgcom/cook1.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a> 
<br>
<CENTER> Best Loyalty Scheme</CENTER>
<CENTER>New York Casino</CENTER><a href="http://www.newyorkcasino.com" target=new><img src="../imgcom/newyork468.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a> 
<br>
<CENTER> Best Casino Software</CENTER>
<CENTER>Ace King Club - Boss Media</CENTER><a href="http://www.acekingclub.com" target=new ><img src="../imgcom/akc.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a> 
<br>

<CENTER> Best Customer Support</CENTER>
<CENTER>Casino Fortune</CENTER><a href="http://www.casinofortune.com" target=new><img src="../imgcom/fortune.gif" width="468" height="60" border="0" alt="OPA APPROVED"></a> 
<br>
<CENTER> Best Personality</CENTER>
<CENTER>Julie Sidwell</CENTER><a href="http://www.gambling.com" target=new ><img src="../imgcom/GamblingcomBanner.gif" width="468" height="60" border="0" alt=""></a> 
<br>

<CENTER> Best Casino Manager</CENTER>
<CENTER>Micki Oyster</CENTER><a href="http://www.kingneptunescasino.com" target=new ><img src="../imgcom/kn.gif" width="468" height="60" border="0" alt="OPA"></a>
<br>
<CENTER> Best Casino Promotions</CENTER>
<CENTER>Inter Casino</CENTER><a href="http://www.intercasino.com/index.php3?498" target=new ><IMG SRC="../imgcom/interc.gif" border=0></a>

  <center>
To contact The OPA <a href="mailto:support@onlineplayersassociation.co.uk?subject=OPA: SUPPORT">CLICK HERE</a><br><br>

 </font><br><br>
          </td>
        </tr>

      </table>
<table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" height=1></td></tr></table>
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr><td bgcolor=#FFFFFF width="1" align=left><img src="../imgcom/clear.gif" alt="" width=1 height=1></td><td colspan=1 height=66 bgcolor=#444444 align=center valign=middle>
<center><a href="http://www.onlineplayersassociation.co.uk"><img src="../banners/olpa.gif" width=468 height=60 border=0></td><td bgcolor=#FFFFFF width="1" align=right><img src="../imgcom/clear.gif" alt="" width=1 height=1></td></tr>
</table><table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" height=1></td></tr></table>
</BODY>
</HTML>

  

