<html>
<head>
</head>
<body>

    <!-- NAME: navi.tpl -->
<HTML>
<HEAD>
<TITLE> O N L I N E - P L A Y E R S - A S S O C I A T I O N  </TITLE>

<style type="text/css">
<!-
A { text-decoration:none }
->
</style>

<STYLE TYPE="text/css">
}
INPUT {
	FONT-FAMILY: verdana,arial,helvetica; FONT-SIZE: 8pt
P {
	COLOR: #ffffff; FONT-FAMILY: verdana,arial,helvetica; FONT-SIZE: 8pt; MARGIN: 0px TEXT-ALIGN: justify
TD {
	COLOR: #ffffff; FONT-FAMILY: verdana,arial,helvetica; FONT-SIZE: 7pt; MARGIN: 0px
H5 {
	COLOR: #ffcc00; FONT-FAMILY: verdana,arial,helvetica; FONT-SIZE: 7pt; MARGIN-BOTTOM: 0px; MARGIN-TOP: 0px; PADDING-BOTTOM: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px
</STYLE>

</HEAD>

<BODY BGCOLOR=000000 LINK=#ffcc00 vlink=#ffcc00>
<CENTER>
<TABLE WIDTH="474" CELLSPACING="0" CELLPADDING="0" border="0"><TR BGCOLOR="#FFFFFF">
<TD colspan=1><IMG SRC="../imgcom/clear.gif" ALT="" HEIGHT=1></TD></TR></TABLE>
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr bgcolor=#ffffff><td bgcolor=#FFFFFF width="1" align=left><img src="../imgcom/clear.gif" alt="" width=1 height=1></td><td colspan=1 height=66 bgcolor=#444444 align=center valign=middle>
<center><a href="http://www.onlineplayersassociation.co.uk"><img src="../banners/olpa.gif" width=468 height=60 border=0></a></td><td bgcolor=#FFFFFF width="1" align=right><img src="../imgcom/clear.gif" alt="" width=1 height=1></td></tr>
</table><table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" height=1></td></tr></table>
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr><td bgcolor=#FFFFFF width="1" align=left><img src="../imgcom/clear.gif" alt="" width=1 height=1></td><TD bgcolor=#ff0000><a href="clear.php3"><img src="../imgcom/clear.gif" width=183 height=10 border=0></a><img src="../imgcom/clear.gif" width=288 height=10></TD><td bgcolor=#FFFFFF width="1" align=right><img src="../imgcom/clear.gif" alt="" width=1 height=1></td></tr>
</table>
<table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" width=474 height=1></td></tr>
</table>
<table width="474" cellspacing="0" cellpadding="0" border="0"><tr>
<td colspan=1><img src="../imgcom/clear.gif" Alt="" width=474 height=5></td></tr>
</table>
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" height=1></td></tr></table>
<!-- END: topban.tpl --><!-- NAME: page1.tpl -->
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr><td bgcolor=#FFFFFF width="1" align=left><img src="../imgcom/clear.gif" alt="" width=1 height=1></td><td colspan=1 bgcolor=#444444 align=left><font face='arial' size='2' color='#ffffff'>&nbsp;<b><A HREF="http://www.onlineplayersassociation.co.uk/casino.php3">Casinos Join</a><IMG SRC="../imgcom/clear.gif" ALT="" WIDTH=15 HEIGHT=1 border=0>  <font face='arial' size='2' color='#ffffff'> <b>  <A HREF="http://www.onlineplayersassociation.co.uk/players.php3">Players Join</a><IMG SRC="../imgcom/clear.gif" ALT="" WIDTH=15 HEIGHT=1 border=0> <A HREF="http://www.onlineplayersassociation.co.uk/supporters.php3">Supporters Join</a><IMG SRC="../imgcom/clear.gif" ALT="" WIDTH=15 HEIGHT=1 border=0><a href="mailto:support@onlineplayersassociation.co.uk?subject=OPA : Support">Contact Us</a><IMG SRC="../imgcom/clear.gif" ALT="" WIDTH=15 HEIGHT=1 border=0><A
HREF="http://www.onlineplayersassociation.co.uk/legal.php3">Legal</a></i></td><td bgcolor=#FFFFFF width="1" align=right><img src="../imgcom/clear.gif" alt="" width=1 height=1></td></tr>
</table><table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" width=474 height=1></td></tr>
</table>
<table width="470" cellspacing="0" cellpadding="0" border="0">
<tr><td><font face='arial' size='2' color='#ffffff'><br>

<a href="http://www.onlineplayersassociation.co.uk" ><img src="../banners/back.gif" border=0></a>
<img src="../imgcom/DISPUTES.gif"><BR><BR><CENTER>
Dispute Resolution<br><br></CENTER><b><br><br>
The commitment shown by Approved Casinos during 2002 has been a solid foundation on which to progress into 2003. 
<br><br>
We managed to recover over $500,000 to Members owed money from unscrupulous online casinos which should be a concern to most right minded people and shows there are still a lot of bad casino operations around. 
<br><br>
This achievement is, whilst commendable, one which concerns us, as it shows players are still being victim to "shady" operators. 
<br><br>
For 2003 we have decided to concentrate our Dispute Resolution Service on OPA Approved Casinos only. 
<br><br>
The reasoning behind this, is at present, some players are ignoring our advice and playing at Non Approved Casinos instead of Approved Casinos who have shown a 100% commitment to customer service and speedy dispute resolution. 
<br><br>
We strongly recommend you only play at OPA Approved Casinos and should you have a dispute or cause for concern with any of our Approved Casinos we will assist and get a speedy resolution. 
<br><br>
Remember All Members can choose which casinos are Approved and which aren't, and this strategy of allowing mass voting will result in everyone's views and experiences of each casino to be heard.
<br><br>

Should you need assistance with a Non Approved Casino may we suggest one of the following respected organisations; 

<br><br>
<a href="mailto:support@onlineplayersassociation.co.uk?subject=dispute resolution: help!">Submit dispute here</a>

 </font><br><br>
          </td>
        </tr>

      </table>
<table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" height=1></td></tr></table>
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr><td bgcolor=#FFFFFF width="1" align=left><img src="../imgcom/clear.gif" alt="" width=1 height=1></td><td colspan=1 height=66 bgcolor=#444444 align=center valign=middle>
<center><a href="http://www.onlineplayersassociation.co.uk"><img src="../banners/olpa.gif" width=468 height=60 border=0></td><td bgcolor=#FFFFFF width="1" align=right><img src="../imgcom/clear.gif" alt="" width=1 height=1></td></tr>
</table><table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" height=1></td></tr></table>
</BODY>
</HTML>

  

