<html>
<head>
</head>
<body>

    <!-- NAME: navi.tpl -->
<HTML>
<HEAD>
<TITLE> O N L I N E - P L A Y E R S - A S S O C I A T I O N  </TITLE>

<style type="text/css">
<!-
A { text-decoration:none }
->
</style>

<STYLE TYPE="text/css">
}
INPUT {
	FONT-FAMILY: verdana,arial,helvetica; FONT-SIZE: 8pt
P {
	COLOR: #ffffff; FONT-FAMILY: verdana,arial,helvetica; FONT-SIZE: 8pt; MARGIN: 0px TEXT-ALIGN: justify
TD {
	COLOR: #ffffff; FONT-FAMILY: verdana,arial,helvetica; FONT-SIZE: 7pt; MARGIN: 0px
H5 {
	COLOR: #ffcc00; FONT-FAMILY: verdana,arial,helvetica; FONT-SIZE: 7pt; MARGIN-BOTTOM: 0px; MARGIN-TOP: 0px; PADDING-BOTTOM: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px
</STYLE>

</HEAD>

<BODY BGCOLOR=000000 LINK=#ffcc00 vlink=#ffcc00>
<CENTER>
<TABLE WIDTH="474" CELLSPACING="0" CELLPADDING="0" border="0"><TR BGCOLOR="#FFFFFF">
<TD colspan=1><IMG SRC="../imgcom/clear.gif" ALT="" HEIGHT=1></TD></TR></TABLE>
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr bgcolor=#ffffff><td bgcolor=#FFFFFF width="1" align=left><img src="../imgcom/clear.gif" alt="" width=1 height=1></td><td colspan=1 height=66 bgcolor=#444444 align=center valign=middle>
<center><a href="http://www.onlineplayersassociation.co.uk"><img src="../banners/olpa.gif" width=468 height=60 border=0></a></td><td bgcolor=#FFFFFF width="1" align=right><img src="../imgcom/clear.gif" alt="" width=1 height=1></td></tr>
</table><table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" height=1></td></tr></table>
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr><td bgcolor=#FFFFFF width="1" align=left><img src="../imgcom/clear.gif" alt="" width=1 height=1></td><TD bgcolor=#ff0000><a href="clear.php3"><img src="../imgcom/clear.gif" width=183 height=10 border=0></a><img src="../imgcom/clear.gif" width=288 height=10></TD><td bgcolor=#FFFFFF width="1" align=right><img src="../imgcom/clear.gif" alt="" width=1 height=1></td></tr>
</table>
<table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" width=474 height=1></td></tr>
</table>
<table width="474" cellspacing="0" cellpadding="0" border="0"><tr>
<td colspan=1><img src="../imgcom/clear.gif" Alt="" width=474 height=5></td></tr>
</table>
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" height=1></td></tr></table>
<!-- END: topban.tpl --><!-- NAME: page1.tpl -->
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr><td bgcolor=#FFFFFF width="1" align=left><img src="../imgcom/clear.gif" alt="" width=1 height=1></td><td colspan=1 bgcolor=#444444 align=left><font face='arial' size='2' color='#ffffff'>&nbsp;<b><A HREF="http://www.onlineplayersassociation.co.uk/casino.php3">Casinos Join</a><IMG SRC="../imgcom/clear.gif" ALT="" WIDTH=15 HEIGHT=1 border=0>  <font face='arial' size='2' color='#ffffff'> <b>  <A HREF="http://www.onlineplayersassociation.co.uk/players.php3">Players Join</a><IMG SRC="../imgcom/clear.gif" ALT="" WIDTH=15 HEIGHT=1 border=0> <A HREF="http://www.onlineplayersassociation.co.uk/supporters.php3">Supporters Join</a><IMG SRC="../imgcom/clear.gif" ALT="" WIDTH=15 HEIGHT=1 border=0><a href="mailto:support@onlineplayersassociation.co.uk?subject=OPA : Support">Contact Us</a><IMG SRC="../imgcom/clear.gif" ALT="" WIDTH=15 HEIGHT=1 border=0><A
HREF="http://www.onlineplayersassociation.co.uk/legal.php3">Legal</a></i></td><td bgcolor=#FFFFFF width="1" align=right><img src="../imgcom/clear.gif" alt="" width=1 height=1></td></tr>
</table><table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" width=474 height=1></td></tr>
</table>
<table width="470" cellspacing="0" cellpadding="0" border="0">
<tr><td><font face='arial' size='2' color='#ffffff'><br>

<a href="http://www.onlineplayersassociation.co.uk" ><img src="../banners/back.gif" border=0></a><img src="../imgcom/opa_supporter.gif"><br><br>
<B>
<CENTER>
The following sites are OPA Supporter sites<br><br></CENTER>

<a href="http://www.gamingbroadcast.com"><img src="../supporters/BRODACAST.gif" width=468 height=60 border=0></a>

<br>
<a href="http://www./casino-help.com"><img src="../supporters/casino-help1.gif" width=468 height=60 border=0></a>


<br>
<a href="http://www.gamemasteronline.com"><img src="../supporters/GMO-banner.gif" width=468 height=60 border=0></a>

<br>

<a href="http://www.bonusfox.com"><img src="../supporters/FOXBAN.gif" width=468 height=60 border=0></a>

<br>

<a href="http://www.casinocity.com"><img src="../supporters/ccity.gif" width=468 height=60 border=0></a>

<br>
<br>
<a href="http://www.casinomeister.com"><img src="../supporters/casinomeister2.gif" width=468 height=60 border=0></a>

<br>
<br>

<a href="http://www.playdayandco.com"><img src="../supporters/playdayandco.gif" width=468 height=60 border=0></a>

<br>


<a href="http://www.casino.co,uk"><img src="../supporters/Luck.gif" width=468 height=60 border=0></a>

<br><a href="http://www.ministryofgaming.com" target=new><img src="../banners/2905.gif" width=468 height=60 border=0></a><br>
<br>
<a href="http://www.fairbet.org" target=new><img src="../banners/2904.gif" width=468 height=60 border=0></a><br>
<br>


<a href="http://www.gamblersdeal.com" target=new><img src="../banners/2903.gif" width=468 height=60 border=0></a><br>

<br>

<a href="http://www.reviewed-casinos.com " target=new><img src="../banners/2901.gif" width=468 height=60 border=0></a><br>
<br>
<a href="http://www.casinogamblinglist.com " target=new><img src="../banners/cgl-1.gif" width=468 height=60 border=0></a><br>
<br>


<a href="http://www.fairbet.com" target=new><img src="../banners/2904.gif" width=468 height=60 border=0></a><br>
<br>

<a href="http://www.portal-casinos.com"><img src="../banners/ban_PC.gif" width=468 height=60 border=0></a><br>
<br>

<a href="http://www.casinorehberi.com" target=new><img src="../banners/20s2.gif" width=468 height=60 border=0></a><br>
<br>

<a href="http://www.casinoruler.com" target=new><img src="../banners/casinoruler_banner2.gif" width=468 height=60 border=0></a><br>
<br>

<a href="http://www.free-internet-gambling.com" target=new><img src="../banners/figbanner2.gif" width=468 height=60 border=0></a><br>
<br>
<br>

<a href="http://www.best-online-casino-directory.com" target=new><img src="../banners/bocd468x60.gif" width=468 height=60 border=0></a><br>
<br>

<a href="tp://www.http://www.thecasinohunter.com " target=new><img src="../banners/hunternew1.gif" width=468 height=60 border=0></a><br>

<br>

<a href="http://www.http://hits4ever.com/onlinecasinoguide"><img src="../supporters/pocg468x60.gif" width=468 height=60 border=0></a>
<br><br>
<a href="http://junglebingo.web1000.com"><img src="../supporters/junglebanner.gif" width=468 height=60 border=0></a>
<br><br>
<a href="http://www.www.bjstats.com/bjcas.htm"><img src="../supporters/bjstats.gif" width=468 height=60 border=0></a>
<br><br>
<a href="http://www.http://www.optimalgambling.com"><img src="../supporters/ogbanner_468.gif" width=468 height=60 border=0></a>
<br><br>



  <center>
 
  

To contact The OPA <a href="mailto:support@onlineplayersassociation.co.uk?subject=OPA: SUPPORT">CLICK HERE</a><br><br>

 </font><br><br>
          </td>
        </tr>

      </table>
<table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" height=1></td></tr></table>
<table width="474" cellspacing="0" cellpadding="0" border="0">
<tr><td bgcolor=#FFFFFF width="1" align=left><img src="../imgcom/clear.gif" alt="" width=1 height=1></td><td colspan=1 height=66 bgcolor=#444444 align=center valign=middle>
<center><a href="http://www.onlineplayersassociation.co.uk"><img src="../banners/olpa.gif" width=468 height=60 border=0></td><td bgcolor=#FFFFFF width="1" align=right><img src="../imgcom/clear.gif" alt="" width=1 height=1></td></tr>
</table><table width="474" cellspacing="0" cellpadding="0" border="0"><tr bgcolor="#FFFFFF">
<td colspan=1><img src="../imgcom/clear.gif" Alt="" height=1></td></tr></table>
</BODY>
</HTML>

  

